version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/all-in-one/jdk8/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/all-in-one/jdk11/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/java/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/rust/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/scala/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad

  - package-ecosystem: docker
    directory: '/nodejs/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
