#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg ZULU_VERSION="8.42.0.23" \
    --build-arg JDK_VERSION="8.0.232" \
    --build-arg SHA256SUM="2735d6e456b9194ec8843e5874ef2820e9e54d00aa4cb19c01174722d65ad7a5" \
    --build-arg SBT_VERSION="1.3.6" \
    --build-arg SCALA_VERSION="2.13.1" \
    --build-arg ALMOND_VERSION="0.9.1" \
    --build-arg IERL_VERSION="0.4.0" \
    --build-arg EVCXR_VERSION="0.4.6" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
