#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg ZULU_VERSION="8.44.0.9" \
    --build-arg JDK_VERSION="8.0.242" \
    --build-arg SHA256SUM="98c7233d2d3b55067ed3ff0a83841f55a2480f19aeb9449f49e0b1ea4465a39b" \
    --build-arg SBT_VERSION="1.3.9" \
    --build-arg SCALA_VERSION="2.13.1" \
    --build-arg ALMOND_VERSION="0.9.1" \
    --build-arg IERL_VERSION="0.4.0" \
    --build-arg EVCXR_VERSION="0.4.6" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
