#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg ALPINE_VERSION="3.12" \
    --build-arg ZULU_VERSION="11.39.15" \
    --build-arg JDK_VERSION="11.0.7" \
    --build-arg SHA256SUM="0de7ac5afede2ddeda399f10c9f9df83f91c9b60481ecf304aa5785ed50f36ce" \
    --build-arg SBT_VERSION="1.3.13" \
    --build-arg SCALA_VERSION="2.13.3" \
    --build-arg ALMOND_VERSION="0.10.2" \
    --build-arg IERL_VERSION="0.4.0" \
    --build-arg NODE_VERSION="lts" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
