#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg UBUNTU_CODENAME="focal" \
    --build-arg JDK_VERSION="11.0.9.1" \
    --build-arg ESUM="6c79bfe8bb06c82b72ef2f293a14becef56b3078d298dc75fda4225cbb2d3d0c" \
    --build-arg ZULU_VERSION="11.43.55" \
    --build-arg SBT_VERSION="1.4.3" \
    --build-arg SCALA_VERSION="2.13.3" \
    --build-arg ALMOND_VERSION="0.10.9" \
    --build-arg IERL_VERSION="0.4.0" \
    --build-arg NODE_VERSION="14.x" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
