#!/usr/bin/env sh
set -eux

echo "------ HOOK START - BUILD -------"
printenv

if [ "$DOCKERFILE_PATH" = "" ]; then
    DOCKERFILE_PATH_ARG=""
else
    DOCKERFILE_PATH_ARG="-f $DOCKERFILE_PATH"
fi

DOCKER_CONTENT_TRUST=1

docker build --build-arg BASE_TAG=${DOCKER_TAG} \
    --build-arg UBUNTU_CODENAME="focal" \
    --build-arg ZULU_VERSION="17.30.15" \
    --build-arg JDK_VERSION="17.0.1" \
    --build-arg ESUM="9b8e4d1e47b02b9c2392462ee82988c189357471de3224c37173fa58e2b25112" \
    --build-arg SBT_VERSION="1.6.1" \
    --build-arg SCALA_VERSION="2.13.4" \
    --build-arg ALMOND_VERSION="0.11.1" \
    --build-arg IERL_VERSION="0.4.0" \
    --build-arg NODE_VERSION="14.x" \
    ${DOCKERFILE_PATH_ARG} -t $IMAGE_NAME .

echo "------ HOOK END - BUILD -------"
